monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists

    handlers:
        main:
            type: rotating_file
            max_files: 14
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event"]
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
        deprecation:
            type: stream
            channels: [deprecation]
            path: php://stderr
        symfony_mailer:
            type: service
            id:   App\Service\Log\EmailHandler