FROM ubuntu:jammy

# Required else the ubuntu installation qill ask for timezone in interactive mode
ARG DEBIAN_FRONTEND=noninteractive;

# `apt-get update` is requirement to be able to install any packages at all, it mustt be called first and MUST be chained
# with some `apt-get` afterwards, as it's some known docker caching issue.
RUN     yes | apt-get update \
    &&  yes | apt-get install software-properties-common \
    &&  yes | apt-get install nano \
    &&  yes | apt-get install wget \
    &&  yes | apt-get install iputils-ping \
    &&  yes | apt-get install curl;

# Install php 8.1
RUN     add-apt-repository ppa:ondrej/php;
RUN     yes | apt-get update \
    &&  yes | apt-get install lsb-release ca-certificates apt-transport-https \
    &&  yes | apt-get install \
    &&  yes | apt-get install php8.1 \
    &&  yes | apt-get install php8.1-bcmath \
    &&  yes | apt-get install php8.1-bz2 \
    &&  yes | apt-get install php8.1-cgi \
    &&  yes | apt-get install php8.1-cli \
    &&  yes | apt-get install php8.1-common \
    &&  yes | apt-get install php8.1-curl \
    &&  yes | apt-get install php8.1-fpm \
    &&  yes | apt-get install php8.1-gd \
    &&  yes | apt-get install php8.1-intl \
    &&  yes | apt-get install php8.1-ldap \
    &&  yes | apt-get install php8.1-mbstring \
    &&  yes | apt-get install php8.1-mysql \
    &&  yes | apt-get install php8.1-opcache \
    &&  yes | apt-get install php8.1-pgsql \
    &&  yes | apt-get install php8.1-readline \
    &&  yes | apt-get install php8.1-soap \
    &&  yes | apt-get install php8.1-xdebug \
    &&  yes | apt-get install php8.1-xml \
    &&  yes | apt-get install php8.1-zip \
    &&  yes | apt-get install php8.1-xdebug;

# Need to expose internal container port to allow mapping it to some port that will be accesible outside of container
EXPOSE 80

# Will set the localhost as the one on which apache should run
# However cannot restart the apache here as it will then bind itself to some other port "HELL KNOWS WHY".
RUN printf "\n# Required to make apache run on 127.0.0.1 \nServerName localhost \n" >> /etc/apache2/apache2.conf;

# Symfony routes wont work without it
RUN a2enmod rewrite;

# Install composer
RUN wget https://getcomposer.org/download/2.7.7/composer.phar \
    && mv composer.phar /usr/local/bin/composer \
    && chmod 777 /usr/local/bin/composer;